# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlphttp/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]
exporters:
  otlphttp/parseablelogs:
    endpoint: "http://parseable:8000"
    headers:
      Authorization: "Basic YWRtaW46YWRtaW4="  # admin:admin in base64
      X-P-Stream: otel-logs
      X-P-Log-Source: otel-logs
      Content-Type: application/json
    encoding: json
    tls:
      insecure: true
  otlphttp/parseablemetrics:
    endpoint: "http://parseable:8000"
    headers:
      Authorization: "Basic YWRtaW46YWRtaW4="  # admin:admin in base64
      X-P-Stream: otel-metrics
      X-P-Log-Source: otel-metrics
      Content-Type: application/json
    encoding: json
    tls:
      insecure: true
  otlphttp/parseabletraces:
    endpoint: "http://parseable:8000"
    headers:
      Authorization: "Basic YWRtaW46YWRtaW4="  # admin:admin in base64
      X-P-Stream: otel-traces
      X-P-Log-Source: otel-traces
      Content-Type: application/json
    encoding: json
    tls:
      insecure: true

service:
  pipelines:
    logs:
      exporters: [otlphttp/parseablelogs]
    metrics:
      exporters: [otlphttp/parseablemetrics, otlphttp/prometheus, debug]
    traces:
      exporters: [otlphttp/parseabletraces, otlp, debug]
